#!/usr/bin/env python3
"""Generate Codex-native project agents from the canonical agent tree.

Codex discovers custom agents from `.codex/agents/*.toml`, but this repo keeps
the canonical definitions in `agents/{core,project}/*.md` so every harness reads
the same contract. This generator emits a thin, deterministic Codex adapter:

  * one TOML file per canonical agent
  * Codex-required `name`, `description`, and `developer_instructions`
  * optional `model_reasoning_effort` only when the source hint maps cleanly

It intentionally does not emit `model` or `sandbox_mode`. Those are session and
machine policy decisions; baking them into generated project files would make
Codex less flexible than Claude Code's current adapter.
"""

import json
import re
import sys
from pathlib import Path


EFFORTS = {"minimal", "low", "medium", "high"}


def split_frontmatter(text):
    """Return (frontmatter_lines, full_text) or (None, full_text)."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    return text[4:end].split("\n"), text


def parse_fields(fm_lines):
    """Extract fields from the repo's regular YAML-ish agent frontmatter."""
    name = None
    desc = None
    codex_effort = None
    claude_effort = None

    i = 0
    while i < len(fm_lines):
        line = fm_lines[i]
        if re.match(r"^name:\s", line):
            name = line.split(":", 1)[1].strip()
        elif re.match(r"^description:\s", line):
            desc = line.split(":", 1)[1].strip()
        elif line.strip() == "harness-hints:":
            i += 1
            harness = None
            while i < len(fm_lines) and (fm_lines[i].startswith("  ") or not fm_lines[i].strip()):
                sub = fm_lines[i]
                h_match = re.match(r"^  (\S+):\s*$", sub)
                e_match = re.match(r"^    effort:\s*(\S+)", sub)
                if h_match:
                    harness = h_match.group(1)
                elif e_match and harness == "codex":
                    codex_effort = e_match.group(1).strip()
                elif e_match and harness == "claude-code":
                    claude_effort = e_match.group(1).strip()
                i += 1
            continue
        i += 1

    effort = codex_effort or claude_effort
    if effort not in EFFORTS:
        effort = None
    return name, desc, effort


def toml_string(value):
    return json.dumps(value, ensure_ascii=False)


def agent_sources(root):
    return sorted((root / "agents" / "core").glob("*.md")) + sorted(
        (root / "agents" / "project").glob("*.md")
    )


def main():
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else root / ".codex" / "agents"
    out.mkdir(parents=True, exist_ok=True)

    written = 0
    skipped = 0
    keep = set()
    by_name = {}

    for src in agent_sources(root):
        text = src.read_text(encoding="utf-8")
        fm_lines, full_text = split_frontmatter(text)
        if fm_lines is None:
            skipped += 1
            continue
        name, desc, effort = parse_fields(fm_lines)
        if not name or not desc:
            skipped += 1
            continue
        if name in by_name:
            print(
                "  WARN  duplicate Codex agent name "
                f"'{name}' ({src} vs {by_name[name]}); keeping first, skipping second.",
                file=sys.stderr,
            )
            skipped += 1
            continue

        by_name[name] = src
        dest = out / f"{src.stem}.toml"
        rel = src.relative_to(root).as_posix()
        lines = [
            "# Generated by agents/scripts/core/gen-codex-agents.py.",
            f"# Source: {rel}",
            "# Do not edit here; edit the canonical agent markdown and re-run setup-harness codex.",
            f"name = {toml_string(name)}",
            f"description = {toml_string(desc)}",
        ]
        if effort:
            lines.append(f"model_reasoning_effort = {toml_string(effort)}")
        lines.append(f"developer_instructions = {toml_string(full_text)}")
        dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
        keep.add(dest.name)
        written += 1

    for stale in out.glob("*.toml"):
        if stale.name not in keep:
            stale.unlink()
            print(f"  prune   .codex/agents/{stale.name} (no canonical source)")

    print(f"  gen-codex-agents  {written} agent(s) -> {out} ({skipped} skipped)")
    if skipped:
        print("  WARN  skipped agent file(s); inspect missing frontmatter fields above if unexpected.")


if __name__ == "__main__":
    main()
