#!/usr/bin/env bash
# locks-render-markdown.sh — render the current refs/locks/* state as Markdown.
#
# Reads all refs/locks/* on the origin remote, parses each claim.json blob,
# and emits a Markdown section per active lock to stdout. The output is the
# canonical human-readable mirror of the ref-based truth.
#
# Until Phase 6 cutover, the result is written to
# `docs/plans/active/_plan-locks.generated.md` by the locks-render GitHub Action.
# At Phase 6 cutover, the rendered content moves into
# `docs/plans/active/_plan-locks.md` itself and that file becomes auto-generated.
#
# Usage:
#   bash agents/scripts/core/locks-render-markdown.sh > docs/plans/active/_plan-locks.generated.md
#
# Optional environment:
#   LOCK_REMOTE                       — git remote name (default: origin)
#   SMATCHET_LOCK_BYPASS_REPO_CHECK   — set to 1 to skip Smatchet repo check
#
# Exit codes:
#   0 — rendered successfully (zero locks emits an empty-state stub)
#   2 — argument / environment / repo-state error

set -euo pipefail

remote="${LOCK_REMOTE:-origin}"
remote_url=$(git config --get "remote.${remote}.url" || true)
[ -n "$remote_url" ] || { echo "locks-render-markdown: remote '$remote' not configured" >&2; exit 2; }
if [ "${SMATCHET_LOCK_BYPASS_REPO_CHECK:-0}" != "1" ]; then
    # Portability: derive the expected repo identifier from project.config.json
    # (project.name) instead of hardcoding "Smatchet", so the portable agents/
    # tree works in another project. Falls back to "Smatchet" when the config is
    # unreadable, so the guard is never weaker than before. Anchored at a path
    # boundary (`/` https, `:` scp-style) per H15; matched case-insensitively.
    _proj_cfg="$(git rev-parse --show-toplevel 2>/dev/null)/project.config.json"
    _proj_name="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["project"]["name"])' "$_proj_cfg" 2>/dev/null || python -c 'import json,sys;print(json.load(open(sys.argv[1]))["project"]["name"])' "$_proj_cfg" 2>/dev/null || printf 'Smatchet')"
    _proj_lc="$(printf '%s' "$_proj_name" | tr '[:upper:]' '[:lower:]')"
    _url_lc="$(printf '%s' "$remote_url" | tr '[:upper:]' '[:lower:]')"
    case "$_url_lc" in
        *[/:]"$_proj_lc"*) : ;;
        *) echo "locks-render-markdown: remote URL '$remote_url' does not look like a $_proj_name repo (set SMATCHET_LOCK_BYPASS_REPO_CHECK=1 to override)" >&2; exit 2 ;;
    esac
fi

PYBIN="${PYBIN:-}"
if [ -z "$PYBIN" ]; then
    for candidate in python python3; do
        if command -v "$candidate" >/dev/null 2>&1 && \
           "$candidate" -c 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)' 2>/dev/null; then
            PYBIN="$candidate"
            break
        fi
    done
fi
[ -n "$PYBIN" ] || { echo "locks-render-markdown: python3 (or python) is required" >&2; exit 2; }

# Refresh local namespace, prune.
git fetch --quiet --prune "$remote" '+refs/locks/*:refs/locks/*' 2>/dev/null || true

# NOTE: deliberately no "Snapshot taken" timestamp here. An embedded
# per-run wall-clock timestamp would make every cron fire produce a
# different file content even when refs/locks/* is unchanged, opening a
# new sync PR every 30 minutes (noise). The canonical "when was this
# regenerated" signal is the git commit timestamp on this file — query
# via `git log -1 --format=%cI docs/plans/active/_plan-locks.generated.md`.

# Link depth: the rendered file lives at docs/plans/active/_plan-locks.generated.md,
# so a REPO-ROOT-relative target needs `../../../` (three levels: active → plans →
# docs → root). `../../` lands in docs/ and reds test-markdown-links.sh on the sync
# PR (#1942). Same for the per-lock originating-plan link below, which interpolates
# an already-root-relative `docs/plans/...` path.
cat <<EOF
# Plan-locks — auto-generated view of \`refs/locks/*\`

> **Source of truth**: the git refs themselves on \`$remote\`. This file is a
> Markdown mirror regenerated by [.github/workflows/locks-render.yml](../../../.github/workflows/locks-render.yml).
> Do not hand-edit — changes are overwritten on next sync.
>
> **Live query**: \`bash agents/scripts/core/locks-show.sh\`
>
> **When was this last regenerated?** Run \`git log -1 --format=%cI docs/plans/active/_plan-locks.generated.md\`.

EOF

refs=$(git for-each-ref --format='%(refname)' refs/locks/ 2>/dev/null || true)

if [ -z "$refs" ]; then
    cat <<'EOF'
## No active plan-locks

_Empty — no slices currently claim a write set. New claims arrive via
`bash agents/scripts/core/lock-claim.sh <slug> <write-set-file>`._
EOF
    exit 0
fi

count=$(printf '%s\n' "$refs" | wc -l | awk '{print $1}')

cat <<EOF
## In-flight locks ($count active)

EOF

for ref in $refs; do
    slug=${ref#refs/locks/}
    claim=$(git cat-file blob "${ref}:claim.json" 2>/dev/null || echo '{}')
    printf '%s' "$claim" | "$PYBIN" -c '
import json, sys

c = json.load(sys.stdin)

def s(key, default=""):
    v = c.get(key, default)
    return v if v not in (None, "") else default

slug    = s("slug", "?")
owner   = s("owner", "?")
branch  = s("branch", "?")
plan    = s("originating_plan", "")
started = s("started", "?")
updated = s("updated", started)
notes   = s("notes", "")
ws      = c.get("write_set") or []

print(f"### `{slug}`")
print()
print(f"- **Owner**: `{owner}`")
print(f"- **Branch**: `{branch}`")
if plan:
    print(f"- **Originating plan**: [`{plan}`](../../../{plan})")
print(f"- **Started**: {started}")
if updated and updated != started:
    print(f"- **Updated**: {updated}")
print(f"- **Write set** ({len(ws)} paths):")
if ws:
    for p in ws:
        print(f"  - `{p}`")
else:
    print("  - _(empty)_")
if notes:
    print(f"- **Notes**: {notes}")
print()
'
done
