#!/usr/bin/env bash
# test-plan-index.sh — keep the shipped-plan index in sync with the archive dir.
#
# Regenerates the table of shipped/archived plans from the actual *.md files in
# the archive directory, into the index file between the markers
#   <!-- BEGIN auto-plan-index --> ... <!-- END auto-plan-index -->
# Surrounding prose (the human §Notes etc.) is never touched.
#
# Modes:
#   (default) / --check   regenerate in memory, diff vs committed; exit 1 on drift
#   --fix                 rewrite the block in place from the live archive
#
# Per row: slug (filename), link (relative href), approx date (first-commit date
# via `git log --follow`), one-line summary (an in-file
# `<!-- index-summary: ... -->` override if present, else the plan's H1 title).
# Output is byte-stable (no timestamps) so --check is deterministic.
#
# Paths are config-driven below — the Phase-D rename (design/archive -> plans/
# shipped, BACKLOG_PLANS.md -> plans/INDEX.md) is a two-line edit here.
set -uo pipefail

ARCHIVE_DIR="${PLAN_INDEX_ARCHIVE_DIR:-docs/plans/shipped}"
INDEX_FILE="${PLAN_INDEX_FILE:-docs/plans/INDEX.md}"
BEGIN_MARK="<!-- BEGIN auto-plan-index -->"
END_MARK="<!-- END auto-plan-index -->"

MODE="check"
for a in "$@"; do
  case "$a" in
    --fix) MODE="fix" ;;
    --check) MODE="check" ;;
    *) echo "usage: $0 [--check|--fix]" >&2; exit 2 ;;
  esac
done

# command -v alone is insufficient on Windows: the python3 Store-alias stub passes it
# but exits 49 when run. Probe each candidate; take the first that actually executes.
PY=""; for _c in python3 python py; do
    _p="$(command -v "$_c" 2>/dev/null)" || continue
    if "$_p" -c "" >/dev/null 2>&1; then PY="$_p"; break; fi
done
[ -z "$PY" ] && { echo "test-plan-index: python not found" >&2; exit 2; }

"$PY" - "$ARCHIVE_DIR" "$INDEX_FILE" "$BEGIN_MARK" "$END_MARK" "$MODE" <<'PY'
import os, re, subprocess, sys

archive_dir, index_file, begin, end, mode = sys.argv[1:6]

def git_first_date(path):
    try:
        git_path = path.replace(os.sep, "/")
        out = subprocess.run(["git", "log", "--follow", "--format=%ad", "--date=short", "--", git_path],
                             capture_output=True, text=True, check=False).stdout.strip().splitlines()
        return out[-1] if out else "—"
    except Exception:
        return "—"

def summary_for(path):
    h1 = ""
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r'^\s*<!--\s*index-summary:\s*(.+?)\s*-->\s*$', line)
            if m:
                return m.group(1).strip()
            if not h1 and line.startswith("# "):
                h1 = line[2:].strip()
    return h1 or "_(summary TODO)_"

if not os.path.isdir(archive_dir):
    print("test-plan-index: archive dir %s not found" % archive_dir, file=sys.stderr); sys.exit(2)

rows = []
for fn in sorted(os.listdir(archive_dir)):
    if not fn.endswith(".md") or fn.startswith("_"):
        continue
    slug = fn[:-3]
    path = os.path.join(archive_dir, fn)
    date = git_first_date(path)
    summ = summary_for(path).replace("|", "\\|")
    # link relative to the index file's directory
    href = os.path.relpath(path, os.path.dirname(index_file)).replace(os.sep, "/")
    rows.append((date, slug, "| [`%s`](%s) | %s | %s |" % (slug, href, date, summ)))

rows.sort(key=lambda r: (r[0], r[1]))
block = [begin,
         "<!-- Generated by agents/scripts/core/test-plan-index.sh — do not hand-edit between the markers.",
         "     Override a row's summary with an `<!-- index-summary: ... -->` comment in the plan file. -->",
         "",
         "| Plan (slug) | Approx. date | One-line summary |",
         "|---|---|---|"]
block += [r[2] for r in rows]
block.append(end)
new_block = "\n".join(block)

with open(index_file, encoding="utf-8") as f:
    content = f.read()

if begin not in content or end not in content:
    print("test-plan-index: markers not found in %s" % index_file, file=sys.stderr)
    print("  add a '%s' / '%s' pair where the shipped-plan table should live." % (begin, end), file=sys.stderr)
    sys.exit(2)

pre = content[:content.index(begin)]
post = content[content.index(end) + len(end):]
rebuilt = pre + new_block + post

if rebuilt == content:
    print("test-plan-index: index up to date (%d plans)" % len(rows))
    print("Passed: 1  Failed: 0")
    sys.exit(0)

if mode == "fix":
    with open(index_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(rebuilt)
    print("test-plan-index: rewrote index (%d plans)" % len(rows))
    print("Passed: 1  Failed: 0")
    sys.exit(0)

# check mode: report drift
print("test-plan-index: DRIFT — shipped-plan index out of sync (%d plans in archive)." % len(rows), file=sys.stderr)
print("  run: bash agents/scripts/core/test-plan-index.sh --fix", file=sys.stderr)
print("Passed: 0  Failed: 1")
sys.exit(1)
PY
