#!/usr/bin/env bash
# test-plan-ref-integrity.sh — every docs/plans/{active,shipped}/<slug>.md path
# referenced anywhere in the tree must resolve to an existing file.
#
# This is the guard that proves the Phase-D rename (docs/design -> docs/plans)
# rewrote every reference, including free-prose paths in C++ comments that the
# markdown-link checker structurally can't see. Also catches a future plan
# rename that leaves a dangling citation.
#
# Skips generated metadata (.understand-anything/) — regenerated by its tool.
set -uo pipefail

cd "$(git rev-parse --show-toplevel)"

# Known pre-existing dangling refs — citations to plans that never existed (or
# illustrative placeholders), dangling as docs/design/<x>.md before the Phase-D
# rename too. Allowlisted so this guard passes on inherited debt while still
# catching any NEW dangling ref. Clean these out separately, then drop here.
#   placeholders: example.md, foo.md (test-data / code-example strings)
#   never-existed plans cited in ADRs/agent prompts: agentic-{coding-handoff,
#     flow-implementation,triage-flow}, visual-regression-bootstrap
#   stale structure refs: README.md, _plan-locks.md (real file is _plan-locks.generated.md)
ALLOW_RE='/(example|foo|bar|baz|agentic-coding-handoff|agentic-flow-implementation|agentic-triage-flow|visual-regression-bootstrap|README|_plan-locks)\.md$'

# Collect every referenced docs/plans/(active|shipped)/<slug>.md across tracked
# files, then assert each exists.
mapfile -t refs < <(git grep -hoE 'docs/plans/(active|shipped)/[A-Za-z0-9._-]+\.md' \
                      -- ':!.understand-anything/' 2>/dev/null | sort -u)

missing=()
for r in "${refs[@]}"; do
  [ -f "$r" ] && continue
  printf '%s\n' "$r" | grep -qE "$ALLOW_RE" && continue   # known pre-existing — skip
  missing+=("$r")
done

if [ "${#missing[@]}" -eq 0 ]; then
  echo "test-plan-ref-integrity: all ${#refs[@]} referenced plan paths resolve."
  echo "Passed: 1  Failed: 0"
  exit 0
fi

echo "test-plan-ref-integrity: ${#missing[@]} dangling plan reference(s):" >&2
for m in "${missing[@]}"; do echo "  $m" >&2; done
echo "Passed: 0  Failed: 1"
exit 1
